### PR TITLE
Fix typo and grammar errors in displayed messages

### LINKED ISSUE #153: [PE-D][Tester D] Typo in rate message usage
Example given has a typo. It should be "rate 1 r/4 re/not too bad.", instead of 1 r/ 4re/not too bad."

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: phualiting/ped#2

### LINKED ISSUE #162: [PE-D][Tester D] Incorrect grammar when find list has one result
It would be better if the message returned "1 activity listed!" when there is only 1 item in the list.
Occurred after using find with time which returns 1 result.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: phualiting/ped#4

### LINKED ISSUE #180: [PE-D][Tester D] Typos in findStatus message usage
Spaces missing

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: phualiting/ped#8

### PR DESCRIPTION
**Pull request by ngquyduc**
Closes #180, closes #162, closes #153

### CODE REVIEW

File: src/main/java/hobbylist/logic/commands/RateCommand.java [hunk 1]
```diff
@@ -29,7 +29,7 @@ public class RateCommand extends Command {
             + "[" + CliSyntax.PREFIX_RATING + "RATING (1-5)] "
             + "[" + CliSyntax.PREFIX_REVIEW + "REVIEW]\n"
             + "Example: " + commandWord + " 1 "
-            + CliSyntax.PREFIX_RATING + " 4"
+            + CliSyntax.PREFIX_RATING + "4" + " "
```
Comment (ZhengLong3) [inline src/main/java/hobbylist/logic/commands/RateCommand.java:32]: I think you can just write `"4 "` instead

**Review by ZhengLong3 — COMMENTED** [review]
LGTM
